### ISSUE TITLE
too complicated when compared to cone

### ISSUE THREAD

**Issue by cauerego** [xuhcc/beancount-mobile#12]
the ledger is a rather permissive standard, from what i can gather in 1 day testing and getting to know it.

this app isn't.

would love it if it was. more like the cone. https://cone.tangential.info/wiki/Mobile-ledgers/

neither seem to be able to edit the text file though, which could be useful.

i will probably stick with cone and ledger on termux for now, but thanks for trying! 😘

**Comment by xuhcc** [comment]
Beancount Mobile is a helper app for [beancount](https://github.com/beancount/beancount) which is not based on ledger standard but is entirely different plain-text accounting tool.

>i will probably stick with cone and ledger on termux for now, but thanks for trying! kissing_heart

Have fun! :smile:
