### ISSUE TITLE
Add support for transaction flags

### ISSUE THREAD

**Issue by Aquan1412** [xuhcc/beancount-mobile#2]
It would be useful if you could set the flag for a new transaction, instead of using the unflagged default "txn" for all new transactions.

**Comment by xuhcc** [comment]
Thanks for suggestion, I'll add this feature in the next release.

**Comment by xuhcc** [comment]
@Aquan1412

Transaction flag added in v1.1.0:

<img width="300" src="https://user-images.githubusercontent.com/1660460/63644001-abe1f200-c6e6-11e9-958b-abc7edd7c1be.png">

By default the flag will switch between `*` and `!`, but it is possible to configure allowed flags with this directive:
```
1970-01-01 custom "bcm_option" "transaction_flags" "['*', '!', '?', '♡']"
```
