### ISSUE TITLE
Internet permissions (and Hello!)

### ISSUE THREAD

**Issue by bradyt** [xuhcc/beancount-mobile#3]
Hello! cone author here. Excited for another mobile plain text accounting app, exploring the problem space with another framework. Feel free to find related communities on IRC, like freenode's #beancount, #plaintextaccounting (linked to matrix), #hledger, #ledger. Looking forward to find inspiration from your app!

I was also wondering if the internet permissions are necessary for your shipped build. Maybe it is only needed for debugging? I wonder if things will work smoothly if you move it to for example

```
App_Resources/Android/src/debug/AndroidManifest.xml
```

Regards!

**Comment by xuhcc** [comment]
Hello! 

Indeed, internet permission is needed only for debug build. Your solution with debug manifest worked perfectly, thanks!
